### ISSUE TITLE
Include native resources into Composite Controller

### ISSUE THREAD

**Issue by kalise** [GoogleCloudPlatform/metacontroller#108]
(As requested in the FAQ)

Hello, we're using a Composite Controller (CC) to control our custom CRD. In our CRD descriptor, we reference few ConfigMaps and Secrets. We want to pass these ConfigMaps and Secrets to the web hook because we need them for creating the children objects. Currently there is no way (for our knowledge) to bind native resources, i.e. ConfigMaps an Secrets to the parent object in CC definition and get them passed to the web  hook.

Our workaround is to simply reference the ConfigMaps and Secrets by name into CRD descriptor (we create a field into the CRD only for this) and then use their name in the hook to build the children. However, we cannot dispose of the configMaps and Secrets when deleting the CRD. 

Another approach is to consider the ConfigMaps and Secrets as children resources and leave the hook to define them. However, this approach is not working because we have to put the content of ConfigMaps and Secrets (config file and credentials) into the CRD descriptor. Think about credentials: we put them in clear text into CRD descriptor and then we create a Secret for the children objects. No sense.

Any suggestion is appreciated.

Thanks
Adriano

**Comment by mikebryant** [comment]
I think this is similar to #98

**Comment by kalise** [comment]
@mkebryant yep

**Comment by kalise** [comment]
@enisoc Yes, in our case, we want just to reference the ConfigMaps/Secrets by name in the parent resource and use them in the hook to build the children. They are in the same namespace of the parent resource. It should be possible to have them in a different namespaces if the namespace is specified into the parent object?

**Comment by enisoc** [comment]
> we want just to reference the ConfigMaps/Secrets by name in the parent resource and use them in the hook to build the children.

OK in that case, I think whatever we end up doing for #98 should also solve this case, so I'll go ahead and close this so we can keep everything in that one thread.

> It should be possible to have them in a different namespaces if the namespace is specified into the parent object?

I looked at the built-in APIs, and it looks like for the most part they require ConfigMaps and Secrets to be in the same namespace (as the Pod, for instance). One exception I see is VolumeSource plugins. Maybe we would start with requiring same namespace like Pod, to keep things simple until there's a clear need for cross-namespace.

**Comment by piersharding** [comment]
Hi - perhaps another example is this https://github.com/kubernetes/kubernetes/issues/36601 - creating run to completion jobs to run on each node.  It would be really handy to be able to specify resources including Node details so that the sync routine did not have to carry an API client to do it.
Thanks,
Piers.
