### ISSUE TITLE
Helm App Operator with Metacontroller

### ISSUE THREAD

**Issue by kalise** [GoogleCloudPlatform/metacontroller#111]
This is what we're thinking, hope it makes sense:

We want to mimic the [Helm App Operator Kit](https://github.com/operator-framework/helm-app-operator-kit) using the Metacontroller framework. Basically we want to turn Metacontroller into a tool to implement Helm charts without using Helm CLI and Tiller but only using kubectl and custom resources.

The main workflow here would be the following:

1) the user gets a Helm chart for Tomcat (as for example) and writes a Tomcat Custom Resource Definition (CRD).
2) the user defines a CC controller having as parent resource the Tomcat custom resource (CR) and, as children, all the objects defined into the chart, e.g. Deploy, Ingress, Services, Secrets, etc..
3) the user writes a simple hook to make sure the parent CR and all the children are there.
4) the user deploys the CRD, the CC, and the Tomcat controller on the Kubernetes cluster.
5) the user can deploy multiple Tomcats CR from the same chart

```
kubectl apply -f tomcat-cr.yaml
tomcat.extensions.example.io/tommy created

kubectl get tomcats
NAME   REV   STATUS    CHART         APP     NAMESPACE
tommy  1        deployed  tomcat-1.0   7.0.35  default
```

We already implemented a prototype to automate the process above (steps 1-4) having as input only the Helm chart. It looks promising.

Here comes the questions: it would be possible to tell the Metacontroller to listen on an external APIs Server instead of the APIs server that started it? The reason is that we want the framework above running on a separate environment (let's call it "Meta Control Plane") leaving only the Tomcat parent (and its CRD) and children resources deployed on the production cluster.

thanks

**Comment by enisoc** [comment]
Interesting ideas!

It sounds like Metacontroller already supports what you'd need to do this all in one cluster, and you're only asking about adding a way to keep Metacontroller and the CompositeController in a separate cluster. Is that correct?

Can you elaborate on the requirements or goals behind wanting to keep Metacontroller in a separate cluster?

Is it important that the CompositeController CRD live in a separate cluster than the Tomcat CRD it works on (and if so, can you share why)? Or is it just that you want the Metacontroller Pod to be running in a separate cluster? That determines whether the Metacontroller Pod needs to talk to multiple API servers, or just one.

Also, are you imagining a 1-to-many correspondence where one "meta control plane" cluster hosts controllers that manage objects in various other clusters? Or would it be 1-to-1 with a "meta control plane" cluster for each target cluster?

**Comment by kalise** [comment]
@enisoc Thanks!

> It sounds like Metacontroller already supports what you'd need to do this all in one cluster, and you're only asking about adding a way to keep Metacontroller and the CompositeController in a separate cluster. Is that correct?

Yes, it is and once the code will be good enough, we'll open source the Helm App Operator.

> Is it important that the CompositeController CRD live in a separate cluster than the Tomcat CRD it works on (and if so, can you share why)? Or is it just that you want the Metacontroller Pod to be running in a separate cluster? That determines whether the Metacontroller Pod needs to talk to multiple API servers, or just one.

This comes from one of our clients. They run multiple k8s clusters on different cloud providers and on-premises too. They are worried about lacking of central management and monitoring solutions across their hybrid multi-cloud environment. We built for them a sort of Meta-Control-Plane to centralise common management and monitoring functions across all clusters. Currently this Meta-Control-Plane is made of standard components, i.e. APIs server, an etcd, and a set of custom components we built ourself to implement the enhanced functionalities. It is running on a single separated VM and it is consumed as a service.

We're thinking to run the Helm App Operator as part of this Meta-Control-Plane with the Meta-Controller and the Custom Controller pods running on it without installing on each cluster. This because we want keep centralised the Helm App Operator in order to deploy applications on different clusters at same time and smoothly move an application from one cluster to another one.

So the Meta-Controller and the Custom Controller should be started and controlled by the Meta-APIs-Server and should run on the Meta-Control-Plane VM. They need to listen on multiple remote APIs Servers at same time in order to deploy the Tomcat parent resource and its children on the remote clusters. So, it's a 1-to-n relationship.

We're just exploring this but not sure if it will work.

**Comment by kalise** [comment]
Also 1-to-1 can be an option. We can imagine to have one Meta-Controller for each remote cluster with each Meta-Controller running in separated namespace of the Meta-Control-Plane.

**Comment by enisoc** [comment]
OK I think I have a better picture. If 1-to-1 is an option, with a separate Metacontroller Pod for each remote cluster, I think we can enable that with a pretty trivial change to Metacontroller. We just need to add command-line flags to let you tell Metacontroller which API server to talk to, and where to look for credentials, instead of the current behavior to use the default in-cluster API access to talk to the same cluster that the Metacontroller Pod itself is in.

In this plan, the webhook Pods could run in the meta-control-plane cluster, not in the remote clusters. Since these webhooks are usually stateless, you could even share one deployment of each webhook handler across all Metacontroller instances.

However, this plan still hinges on the question of whether it's OK for the CompositeController definitions to live in each remote cluster. If the end users have admin access on the remote clusters, then they would be able to see and modify/break the custom controllers by editing the CompositeController objects that live in their clusters. Is that a deal-breaker for this plan?

If so, then we would need to teach Metacontroller to look at CompositeController/DecoratorController objects in one API server (the meta-control-plane API server), but manage objects in a different API server. This might be feasible, but it's more complicated than the simple plan above, so I'd only want to consider it if it's necessary.

Another question, if the CompositeController definitions need to live in the meta-control-plane API server: Would you expect each CompositeController to apply across all remote clusters, or would you need to be able to specify to which remote clusters a given CompositeController applies? The latter would probably require solving #90 and then having each per-remote-cluster Metacontroller instance look only at CompositeController objects in one namespace. Again, that should be feasible, but I'm trying to understand the scope of work that would be needed.

**Comment by kalise** [comment]
@enisoc Thanks for your interest in this. We found Metacontroller a very flexible and useful tool.

> However, this plan still hinges on the question of whether it's OK for the CompositeController definitions to live in each remote cluster.

Ideally, the Helm App Controller (let's call it) should be invisible to the users. They only need to pick a Helm Chart from a catalog, push a button and get with a CRD, a CR and a set of children running on the remote cluster of their choice. So the CC descriptor should be on the Meta-Control-Plane along with with the Meta-Controller pod, the webhook, and all the required RBAC rules.

However, because we're just experimenting, a quick and dirty solution with CC running on remote cluster can be sufficient to proof our idea to the customer.

> I think we can enable that with a pretty trivial change to Metacontroller. We just need to add command-line flags to let you tell Metacontroller which API server to talk to, and where to look for credentials

How much trivial this change would be? Do you think to be able to release it quickly? 

> Would you expect each CompositeController to apply across all remote clusters, or would you need to be able to specify to which remote clusters a given CompositeController applies? 

A Composite Controller is automatically generated for each Helm Chart and it seems more chart related than cluster related. So it will be applicable to all the remote clusters. May be in the future, the ability to specify which cluster a CC is applicable can give further flexibility to the framework but for now it seems not a strong requirement for us.

Thanks

**Comment by enisoc** [comment]
I sent out #113 for the addition of the command-line flag to tell Metacontroller to talk to a remote API server. This should let you start experimenting with hosting Metacontroller and the webhooks out-of-cluster.

For the longer-term plan, I also realized there's another question we'd need to consider. For CompositeController rolling updates, Metacontroller stores historical controller specs in a ControllerRevision resource. These objects are namespaced, and meant to live in the same namespace as the original controller specs (e.g. as the Tomcat object). We'd need to think about whether it makes sense to keep these in each remote cluster, or to rework ControllerRevision so they can all live in the meta-control-plane cluster without conflicting (e.g. if multiple remote clusters have objects of the same name).

**Comment by kalise** [comment]
@enisoc awesome! Now we can start to experiment. Once we have a clear picture, we can start to think for a long-term solution, including how to deal with ControllerRevision resource.

Is this the right way to enable metacontroller to talk with the remote server? The kubeconfig file with credentials will be passed as ConfigMap. 

```
      - image: metacontroller/metacontroller:latest
        name: metacontroller
        resources:
          requests:
            cpu: 100m
        command: ["/usr/bin/metacontroller"]
        args:
        - --logtostderr
        - -v=6
        - --discovery-interval=20s
        - --client-config-path=/path/to/the/kubeconfig
```

**Comment by enisoc** [comment]
> Is this the right way to enable metacontroller to talk with the remote server? The kubeconfig file with credentials will be passed as ConfigMap.

Yup, that should do it.

**Comment by kalise** [comment]
@enisoc let you know it works!

**Comment by asherlporetz** [comment]
Would be nice to have something like:
```yaml
apiVersion: metacontroller.k8s.io/v1alpha1
kind: HelmTemplateController
metadata:
  name: redis-controller
spec:
  generateSelector: true
  repo: https://kubernetes-charts.storage.googleapis.com
  chart: redis
  version: 4.0.1
  # or package: https://kubernetes-charts.storage.googleapis.com/redis-4.0.1.tgz
```
and given a crd `redis.myorg.com` can be used as
```yaml
apiVersion: myorg.com/v1
kind: Redis
metadata:
  name: my-redis
# spec is the values passed to helm  
spec:
  image:
    registry: docker.io
    repository: bitnami/redis
  rbac:
    create: false
```
and internally will just use the output of `helm template` and not create tiller history configmaps/secrets

**Comment by pragyamehta** [comment]
@kalise Did the "--client-config-path" option work for you?

**Comment by arielb135** [comment]
@kalise are you inputing the entire helm chart tree? and the custom CRD you have affect only the values?
if so, how are you exactly rendering the chart? does you controller have helm installed? does it take it from a repository?

**Comment by kalise** [comment]
Close the issue as the project looks stalled
