### ISSUE TITLE
Metacontroller cannot be `go get`

### ISSUE THREAD

**Issue by silverlyra** [GoogleCloudPlatform/metacontroller#118]
I'm writing a composite controller in Go, and I thought it'd be convenient to import [`CompositeController`](https://github.com/GoogleCloudPlatform/metacontroller/blob/master/apis/metacontroller/v1alpha1/types.go) from this codebase so that I can `json.Unmarshal` metacontroller's request into its actual type.

The `v1alpha1` package has a canonical import path:

```go
package v1alpha1 // import "k8s.io/metacontroller/apis/metacontroller/v1alpha1"
```

but k8s.io’s `?go-get` implementation assumes a requested package is under the kubernetes github org:

```sh
curl https://k8s.io/metacontroller?go-get=1
```

```html
<meta name="go-import"
      content="k8s.io/metacontroller
               git https://github.com/kubernetes/metacontroller">
```

`go get` then fails for this package.

**Comment by enisoc** [comment]
I've been meaning to rename the import path to `metacontroller.app`, which is a domain we actually control (unlike `k8s.io`). It should be pretty straightforward so I gave it a shot in #119.

After that merges, you should be able to `go get metacontroller.app`. You'll also need to change the way you import packages from metacontroller:

```go
import "metacontroller.app/apis/metacontroller/v1alpha1"
```

**Comment by enisoc** [comment]
Correction: `go get metacontroller.app` will download the code, but it won't build because we don't check in the `vendor` dir, so you'd have to run `dep ensure` first. However, I think it will work if you use `dep` on your own project, and depend on a package within `metacontroller.app`. Let me know if that part doesn't work.

**Comment by silverlyra** [comment]
great! thanks so much. we are using `dep`; this is perfect.
