### ISSUE TITLE
Installation manifests aren't up-to-date

### ISSUE THREAD

**Issue by silverlyra** [GoogleCloudPlatform/metacontroller#120]
I found myself scratching my head for awhile after trying to use metacontroller to implement a composite controller for a cluster-scoped resource.

```
I1106 23:22:29.657576       1 controller.go:382] sync Parent /name
I1106 23:22:29.657601       1 controller.go:387] Parent /name has been deleted
```

Since the docs mention cluster-scoped parents, and #71 seemed to have landed it, I wasn’t sure why it wouldn't work.

Then I took a closer look in [the manifest I'd used to install it](https://raw.githubusercontent.com/GoogleCloudPlatform/metacontroller/master/manifests/metacontroller.yaml), and found I'd installed the 0.2 tag, which at this point is five months old.

The version a user will install if they follow the installation docs is now quite out of sync with the behavior described in the rest of the docs. Are there plans to release a new tag soon? If not, might I suggest switching that manifest to `latest`?

(metacontroller is awesome and it's already saved me so much time. thank you!)

**Comment by enisoc** [comment]
Thanks for reporting! I've tagged [v0.3.0](https://github.com/GoogleCloudPlatform/metacontroller/releases/tag/v0.3.0) and updated the manifest to use it.
