### ISSUE TITLE
metacontroller does not pick up on updates to webhooks

### ISSUE THREAD

**Issue by jiancheung** [GoogleCloudPlatform/metacontroller#158]
I ran into an issue where I updated a CompositeController's webhook and applied it, but metacontroller did not pick up the changes.
It continued to sync to the old webhook url.

It picks up on the new webhook url after I manually deleted the metacontroller pod to get it to restart.

**Comment by enisoc** [comment]
I haven't been able to reproduce this yet. Can you give some details on the steps that I should try?

It would also help if you can share anything that looks relevant from the Metacontroller logs. Around the time when you apply an update to the CompositeController, you should see something like this:

```
Shutting down XYZ CompositeController
[...]
Starting XYZ CompositeController
```

Do you see anything like that?

**Comment by jiancheung** [comment]
Huh interested... I just tested this again and it seems fine. My bad. If I notice anything weird again, I'll re-open with a reproducible test case.
Thanks for taking a look @enisoc !
