### ISSUE TITLE
CompositeController shouldn't allow empty parent selector.

### ISSUE THREAD

**Issue by enisoc** [GoogleCloudPlatform/metacontroller#25]
A key feature of CompositeController is that it tracks which objects of a given type are yours, and hides from you any objects of that type that you don't own. This mechanism is defeated if the parent selector is empty, since there's no way to distinguish things you want from things you don't.

There might be legitimate use cases for a controller that selects everything of a given type, but I don't think it should be allowed by default in CompositeController, since more often than not an empty selector is unintentional. For example, this can happen if the parent object does not have the expected, duck-typed `spec.selector` (either because it's missing, or it's the old-style selector like in RC or Service).

**Comment by groner** [comment]
In my initial evaluation of metacontroller, I created a composite controller with a v1/configmaps child resource and no selector.  This resulted in the compositecontroller deleting all the configmaps in that namespace.

This wasn't a big problem in my development environment, but it could be an unpleasant surprise for someone if they decided to test this in a less isolated environment.

**Comment by enisoc** [comment]
Hm that's a good point. I've also had a similar concern with PVCs. It's unfortunate that StatefulSet does not claim the PVCs it creates in any way, so they appear as orphans. If the label selector matches, another controller like CatSet might adopt and delete the PVCs (because they aren't part of the desired state).

Maybe in addition to bailing out if the selector is empty, we should consider limiting the adoption logic to more confined scenarios. It seems rare that people writing custom controllers really want to take ownership of existing objects.

For now, I'll prioritize adding the check for an empty selector since the case you pointed out is a potentially nasty one. Thanks for reporting!
