### ISSUE TITLE
Following build instrctions fails

### ISSUE THREAD

**Issue by soumyapanigrahi-github** [GoogleCloudPlatform/metacontroller#49]
Below are the build instructions to build metacontroller:
go get -u k8s.io/code-generator/cmd/{lister,client,informer,deepcopy}-gen
dep ensure
make

Following the steps as mentioned in build instructions fails at "dep ensure" step:
Solving failure: remote repository at https://github.com/kubernetes/metacontroller does not exist, or is inaccessible: fatal: could not read Username for 'https://github.com': terminal prompts disabled
: exit status 128

**Comment by soumyapanigrahi-github** [comment]
Output of dep ensure dry run.

dep ensure -v -dry-run
found 1 errors in the package tree:
import root "" is not a prefix for the package's declared canonical path ""
Root project is "github.com/GoogleCloudPlatform/metacontroller"
 22 transitively valid internal packages
 47 external packages imported from 6 projects
(0)   ✓ select (root)
(1)	? attempt github.com/golang/glog with 1 pkgs; at least 1 versions to try
(1)	    try github.com/golang/glog@master
(1)	✓ select github.com/golang/glog@master w/1 pkgs
(2)	? attempt github.com/google/go-jsonnet with 2 pkgs; at least 1 versions to try
(2)	    try github.com/google/go-jsonnet@master
(2)	✓ select github.com/google/go-jsonnet@master w/3 pkgs
(3)	? attempt k8s.io/apimachinery with 15 pkgs; at least 1 versions to try
(3)	    try k8s.io/apimachinery@kubernetes-1.9.1
(3)	✓ select k8s.io/apimachinery@kubernetes-1.9.1 w/32 pkgs
(4)	? attempt github.com/davecgh/go-spew with 1 pkgs; at least 1 versions to try
(4)	    try github.com/davecgh/go-spew@v1.1.0
(4)	✓ select github.com/davecgh/go-spew@v1.1.0 w/1 pkgs
(5)	? attempt github.com/ghodss/yaml with 1 pkgs; at least 1 versions to try
(5)	    try github.com/ghodss/yaml@v1.0.0
(5)	✓ select github.com/ghodss/yaml@v1.0.0 w/1 pkgs
(6)	? attempt github.com/json-iterator/go with 1 pkgs; at least 1 versions to try
(6)	    try github.com/json-iterator/go@1.1.2
(6)	✓ select github.com/json-iterator/go@1.1.2 w/1 pkgs
(7)	? attempt github.com/google/gofuzz with 1 pkgs; at least 1 versions to try
(7)	    try github.com/google/gofuzz@master
(7)	✓ select github.com/google/gofuzz@master w/1 pkgs
(8)	? attempt github.com/go-openapi/spec with 1 pkgs; at least 1 versions to try
(8)	    try github.com/go-openapi/spec@master
(8)	✓ select github.com/go-openapi/spec@master w/1 pkgs
(9)	? attempt github.com/go-openapi/jsonpointer with 1 pkgs; at least 1 versions to try
(9)	    try github.com/go-openapi/jsonpointer@master
(9)	✓ select github.com/go-openapi/jsonpointer@master w/1 pkgs
(10)  ? attempt k8s.io/kube-openapi with 1 pkgs; at least 1 versions to try
(10)      try k8s.io/kube-openapi@master
(10)  ✓ select k8s.io/kube-openapi@master w/1 pkgs
(11)  ? attempt github.com/emicklei/go-restful with 1 pkgs; at least 1 versions to try
(11)      try github.com/emicklei/go-restful@v2.6.0
(11)  ✓ select github.com/emicklei/go-restful@v2.6.0 w/2 pkgs
(12)  ? attempt github.com/modern-go/reflect2 with 1 pkgs; at least 1 versions to try
(12)      try github.com/modern-go/reflect2@1.0.0
(12)  ✓ select github.com/modern-go/reflect2@1.0.0 w/1 pkgs
(13)  ? attempt github.com/go-openapi/jsonreference with 1 pkgs; at least 1 versions to try
(13)      try github.com/go-openapi/jsonreference@master
(13)  ✓ select github.com/go-openapi/jsonreference@master w/1 pkgs
(14)  ? attempt github.com/PuerkitoBio/purell with 1 pkgs; at least 1 versions to try
(14)      try github.com/PuerkitoBio/purell@v1.1.0
(14)  ✓ select github.com/PuerkitoBio/purell@v1.1.0 w/1 pkgs
(15)  ? attempt github.com/PuerkitoBio/urlesc with 1 pkgs; at least 1 versions to try
(15)      try github.com/PuerkitoBio/urlesc@master
(15)  ✓ select github.com/PuerkitoBio/urlesc@master w/1 pkgs
(16)  ? attempt k8s.io/client-go with 7 pkgs; at least 1 versions to try
(16)      try k8s.io/client-go@v6.0.0
(16)  ✓ select k8s.io/client-go@v6.0.0 w/17 pkgs
(17)  ? revisit k8s.io/apimachinery to add 10 pkgs
(17)    ✓ include 36 more pkgs from k8s.io/apimachinery@kubernetes-1.9.1
(17)  ? attempt github.com/golang/protobuf with 1 pkgs; at least 1 versions to try
(18)      try github.com/golang/protobuf@v1.0.0
(18)  ✓ select github.com/golang/protobuf@v1.0.0 w/1 pkgs
(18)  ? attempt github.com/juju/ratelimit with 1 pkgs; at least 1 versions to try
(19)      try github.com/juju/ratelimit@1.0.1
(19)  ✓ select github.com/juju/ratelimit@1.0.1 w/1 pkgs
(19)  ? attempt github.com/go-openapi/swag with 1 pkgs; at least 1 versions to try
(20)      try github.com/go-openapi/swag@master
(20)  ✓ select github.com/go-openapi/swag@master w/1 pkgs
(20)  ? attempt gopkg.in/yaml.v2 with 1 pkgs; at least 1 versions to try
(21)      try gopkg.in/yaml.v2@v2.1.1
(21)  ✓ select gopkg.in/yaml.v2@v2.1.1 w/1 pkgs
(21)  ? attempt github.com/modern-go/concurrent with 1 pkgs; at least 1 versions to try
(22)      try github.com/modern-go/concurrent@1.0.3
(22)  ✓ select github.com/modern-go/concurrent@1.0.3 w/1 pkgs
(22)  ? attempt github.com/peterbourgon/diskv with 1 pkgs; at least 1 versions to try
(23)      try github.com/peterbourgon/diskv@v2.0.1
(23)  ✓ select github.com/peterbourgon/diskv@v2.0.1 w/1 pkgs
(23)  ? attempt github.com/gregjones/httpcache with 2 pkgs; at least 1 versions to try
(24)      try github.com/gregjones/httpcache@master
(24)  ✓ select github.com/gregjones/httpcache@master w/2 pkgs
(24)  ? attempt github.com/googleapis/gnostic with 1 pkgs; at least 1 versions to try
(25)      try github.com/googleapis/gnostic@v0.1.0
(25)  ✓ select github.com/googleapis/gnostic@v0.1.0 w/3 pkgs
(25)  ? revisit github.com/golang/protobuf to add 2 pkgs
(26)    ✓ include 5 more pkgs from github.com/golang/protobuf@v1.0.0
(25)  ? attempt k8s.io/kubernetes with 1 pkgs; at least 1 versions to try
(27)      try k8s.io/kubernetes@v1.9.4
(27)  ✓ select k8s.io/kubernetes@v1.9.4 w/1 pkgs
(26)  ? attempt github.com/gogo/protobuf with 2 pkgs; at least 1 versions to try
(28)      try github.com/gogo/protobuf@v1.0.0
(28)  ✓ select github.com/gogo/protobuf@v1.0.0 w/2 pkgs
(27)  ? attempt github.com/spf13/pflag with 1 pkgs; at least 1 versions to try
(29)      try github.com/spf13/pflag@v1.0.0
(29)  ✓ select github.com/spf13/pflag@v1.0.0 w/1 pkgs
(28)  ? attempt github.com/google/btree with 1 pkgs; at least 1 versions to try
(30)      try github.com/google/btree@master
(30)  ✓ select github.com/google/btree@master w/1 pkgs
(29)  ? attempt golang.org/x/net with 1 pkgs; at least 1 versions to try
(31)      try golang.org/x/net@master
(31)  ✓ select golang.org/x/net@master w/1 pkgs
(30)  ? attempt github.com/mailru/easyjson with 2 pkgs; at least 1 versions to try
(32)      try github.com/mailru/easyjson@master
(32)  ✓ select github.com/mailru/easyjson@master w/3 pkgs
(31)  ? revisit golang.org/x/net to add 1 pkgs
(33)    ✓ include 1 more pkgs from golang.org/x/net@master
(31)  ? attempt k8s.io/api with 28 pkgs; at least 1 versions to try
(34)      try k8s.io/api@master
(34)  ✓ select k8s.io/api@master w/28 pkgs
(32)  ? revisit k8s.io/apimachinery to add 2 pkgs
(35)    ✓ include 2 more pkgs from k8s.io/apimachinery@kubernetes-1.9.1
(32)  ? attempt github.com/petar/GoLLRB with 1 pkgs; at least 1 versions to try
(36)      try github.com/petar/GoLLRB@master
(36)  ✓ select github.com/petar/GoLLRB@master w/1 pkgs
(33)  ? attempt golang.org/x/text with 2 pkgs; at least 1 versions to try
(37)      try golang.org/x/text@v0.3.0
(37)  ✓ select golang.org/x/text@v0.3.0 w/14 pkgs
(34)  ? attempt github.com/hashicorp/golang-lru with 1 pkgs; at least 1 versions to try
(38)      try github.com/hashicorp/golang-lru@master
(38)  ✓ select github.com/hashicorp/golang-lru@master w/2 pkgs
(35)  ? revisit golang.org/x/net to add 1 pkgs
(39)    ✓ include 4 more pkgs from golang.org/x/net@master
(35)  ? revisit golang.org/x/text to add 2 pkgs
(40)    ✓ include 7 more pkgs from golang.org/x/text@v0.3.0
(41)    ← no more versions of k8s.io/metacontroller to try; begin backtrack
(40)  ← backtrack: popped 7 pkgs from golang.org/x/text
(39)  ← backtrack: popped 4 pkgs from golang.org/x/net
(38)  ← backtrack: no more versions of github.com/hashicorp/golang-lru to try
(37)  ← backtrack: no more versions of golang.org/x/text to try
(36)  ← backtrack: no more versions of github.com/petar/GoLLRB to try
(35)  ← backtrack: popped 2 pkgs from k8s.io/apimachinery
(34)  ← backtrack: no more versions of k8s.io/api to try
(33)  ← backtrack: popped 1 pkgs from golang.org/x/net
(32)  ← backtrack: no more versions of github.com/mailru/easyjson to try
(31)  ← backtrack: no more versions of golang.org/x/net to try
(30)  ← backtrack: no more versions of github.com/google/btree to try
(29)  ← backtrack: no more versions of github.com/spf13/pflag to try
(28)  ← backtrack: no more versions of github.com/gogo/protobuf to try
(27)  ← backtrack: no more versions of k8s.io/kubernetes to try
(26)  ← backtrack: popped 5 pkgs from github.com/golang/protobuf
(25)  ← backtrack: no more versions of github.com/googleapis/gnostic to try
(24)  ← backtrack: no more versions of github.com/gregjones/httpcache to try
(23)  ← backtrack: no more versions of github.com/peterbourgon/diskv to try
(22)  ← backtrack: no more versions of github.com/modern-go/concurrent to try
(21)  ← backtrack: no more versions of gopkg.in/yaml.v2 to try
(20)  ← backtrack: no more versions of github.com/go-openapi/swag to try
(19)  ← backtrack: no more versions of github.com/juju/ratelimit to try
(18)  ← backtrack: no more versions of github.com/golang/protobuf to try
(17)  ← backtrack: popped 36 pkgs from k8s.io/apimachinery
(16)  ← backtrack: no more versions of k8s.io/client-go to try
(15)  ← backtrack: no more versions of github.com/PuerkitoBio/urlesc to try
(14)  ← backtrack: no more versions of github.com/PuerkitoBio/purell to try
(13)  ← backtrack: no more versions of github.com/go-openapi/jsonreference to try
(12)  ← backtrack: no more versions of github.com/modern-go/reflect2 to try
(11)  ← backtrack: no more versions of github.com/emicklei/go-restful to try
(10)  ← backtrack: no more versions of k8s.io/kube-openapi to try
(9)	← backtrack: no more versions of github.com/go-openapi/jsonpointer to try
(8)	← backtrack: no more versions of github.com/go-openapi/spec to try
(7)	← backtrack: no more versions of github.com/google/gofuzz to try
(6)	← backtrack: no more versions of github.com/json-iterator/go to try
(5)	← backtrack: no more versions of github.com/ghodss/yaml to try
(4)	← backtrack: no more versions of github.com/davecgh/go-spew to try
(3)	← backtrack: no more versions of k8s.io/apimachinery to try
(2)	← backtrack: no more versions of github.com/google/go-jsonnet to try
(1)	← backtrack: no more versions of github.com/golang/glog to try
  ✗ solving failed

Solver wall times by segment:
     b-source-exists: 13.123260065s
         b-list-pkgs: 10.265302051s
              b-gmal:   6.53116632s
  b-deduce-proj-root:  330.198983ms
            unselect:  130.493848ms
             satisfy:  130.410013ms
         select-atom:  119.197119ms
            new-atom:    3.145236ms
         select-root:     805.865µs
           backtrack:     635.642µs
               other:     199.138µs
            add-atom:      72.583µs

  TOTAL: 30.634886863s

Solving failure: remote repository at https://github.com/kubernetes/metacontroller does not exist, or is inaccessible: fatal: could not read Username for 'https://github.com': terminal prompts disabled
: exit status 128

**Comment by soumyapanigrahi-github** [comment]
I get the following error while doing a "go get" on github.com/GoogleCloudPlatform/metacontroller

# cd .; git clone https://github.com/kubernetes/metacontroller /Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller
Cloning into '/Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package k8s.io/metacontroller/apis/metacontroller/v1alpha1: exit status 128
package k8s.io/metacontroller/client/generated/clientset/internalclientset: cannot find package "k8s.io/metacontroller/client/generated/clientset/internalclientset" in any of:
	/usr/local/go/src/k8s.io/metacontroller/client/generated/clientset/internalclientset (from $GOROOT)
	/Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller/client/generated/clientset/internalclientset (from $GOPATH)
package k8s.io/metacontroller/client/generated/informer/externalversions: cannot find package "k8s.io/metacontroller/client/generated/informer/externalversions" in any of:
	/usr/local/go/src/k8s.io/metacontroller/client/generated/informer/externalversions (from $GOROOT)
	/Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller/client/generated/informer/externalversions (from $GOPATH)
package k8s.io/metacontroller/controller/composite: cannot find package "k8s.io/metacontroller/controller/composite" in any of:
	/usr/local/go/src/k8s.io/metacontroller/controller/composite (from $GOROOT)
	/Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller/controller/composite (from $GOPATH)
package k8s.io/metacontroller/controller/decorator: cannot find package "k8s.io/metacontroller/controller/decorator" in any of:
	/usr/local/go/src/k8s.io/metacontroller/controller/decorator (from $GOROOT)
	/Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller/controller/decorator (from $GOPATH)
package k8s.io/metacontroller/dynamic/clientset: cannot find package "k8s.io/metacontroller/dynamic/clientset" in any of:
	/usr/local/go/src/k8s.io/metacontroller/dynamic/clientset (from $GOROOT)
	/Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller/dynamic/clientset (from $GOPATH)
package k8s.io/metacontroller/dynamic/discovery: cannot find package "k8s.io/metacontroller/dynamic/discovery" in any of:
	/usr/local/go/src/k8s.io/metacontroller/dynamic/discovery (from $GOROOT)
	/Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller/dynamic/discovery (from $GOPATH)
package k8s.io/metacontroller/dynamic/informer: cannot find package "k8s.io/metacontroller/dynamic/informer" in any of:
	/usr/local/go/src/k8s.io/metacontroller/dynamic/informer (from $GOROOT)
	/Users/soumyap/Desktop/Learning/Projects/Go/src/k8s.io/metacontroller/dynamic/informer (from $GOPATH)

**Comment by enisoc** [comment]
It's a known issue that `go get` doesn't work, likely because of the fake `k8s.io/metacontroller` import path.

I haven't had problems with dep though. Do you have the latest version of dep? I just updated mine to v0.4.1 and `dep ensure` still works for me.

Where is the cloned repo relative to your `$GOPATH`? I have some updated build instructions that show more clearly where things should be:

https://metacontroller.netlify.com/contrib/build/

**Comment by soumyapanigrahi-github** [comment]
@enisoc thanks for the help.
The issue was with k8s.io/metacontroller import path.
It went away after I moved the code to  k8s.io/metacontroller w.r.t to my GOROOT/src.
Closing the ticket.
