### ISSUE TITLE
Metacontroller logo

### ISSUE THREAD

**Issue by nightsoundars** [GoogleCloudPlatform/metacontroller#53]
Hi I think this project needs a beautiful logo. I can contribute project by designing a logo...

**Comment by enisoc** [comment]
I'm not sure this project has much need for a logo, but you're welcome to propose something.

Alternatively, if you're looking to contribute to open source with your graphic design skills, I'd love to see if you have thoughts on how to visually represent some of the technical concepts we try to explain in the [user docs](https://metacontroller.app/concepts/). I took a shot at this in some [slides](https://docs.google.com/presentation/d/1tfe-C0GQL2JmBlAGxACF8VtKyY9ZdTJcwuC1p3S7N9M/edit?usp=sharing) but I'm definitely not a graphic designer.
