### ISSUE TITLE
Installation instructions end up using an old build of metacontroller

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/metacontroller#67]
The installation documentation references the manifest file which references an older docker image.

https://github.com/GoogleCloudPlatform/metacontroller/blob/master/manifests/metacontroller.yaml#L66

References metacontroller/metacontroller:0.2. Should it reference latest?

**Comment by enisoc** [comment]
The intention is to encourage people to use a pinned version tag when they deploy it, so they have control over when to update to new versions. Sometimes it does make sense to use latest, like when doing testing or active development. In that case, I recommend using something like this to override the tag:

https://metacontroller.app/contrib/build/#skaffold-build

**Comment by nikhilk** [comment]
Generally agree with being explicit rather than relying on how latest is resolved when deploying.

I thought I saw behavior where 0.2 was different than what was documented, hence I thought I'd capture this here, but I think it was due to my user error (as discussed offline).

So I'll go ahead and close this out.
