### ISSUE TITLE
Feature request to include some metadata on sync hook requests

### ISSUE THREAD

**Issue by nikhilk** [GoogleCloudPlatform/metacontroller#68]
It would be interesting to know which sync requests were made because of a refresh sync interval. Perhaps this could be a flag on the request.

Thinking more generally, would it be interesting in expanding this to be an enum indicating if the request is due to parent resource changing, or a child resource changing, or a refresh interval?

**Comment by enisoc** [comment]
Similar to my comment on https://github.com/GoogleCloudPlatform/metacontroller/issues/69#issuecomment-406111662, my first impression is that knowing why the `sync` hook was called would be a Kubernetes controller anti-pattern.

Can you give a concrete example of how this information would be used?

**Comment by nikhilk** [comment]
Here is a concrete example -- I want to use resync to launch another job (and quite possibly outside of the k8s cluster, eg. a Dataflow job) on a timer/cron.

This is directly along the lines of what the doc at https://metacontroller.app/api/compositecontroller/ says:

> Sometimes you may want to sync periodically even if nothing has changed in the Kubernetes API objects, either to simply observe the passage of time, or because your hook takes external state into account. For example, CronJob uses a periodic resync to check whether it’s time to start a new Job.

Now its possible my controller creates a cron job as one of its child resources, rather than itself doing the scheduled work, but ultimately this only defers the problem to another controller in the system - something needs to know whether its being invoked because some config/spec changed, because some child changed, or because time passed.

Or am I missing something?

**Comment by nikhilk** [comment]
Thanks for the writeup, and taking the time to explain in detail!
It suggests some different ways to think about the scenario, and will do so/try implementing it along those lines.
