### ISSUE TITLE
Removing labels/annotations

### ISSUE THREAD

**Issue by mgoodness** [GoogleCloudPlatform/metacontroller#72]
My DecoratorController is able to apply labels & annotations to resources (in my case, Namespaces) by returning corresponding maps. Is there a mechanism for removing them? Returning empty maps doesn't seem to do the job.

**Comment by enisoc** [comment]
The returned map is merged into existing values, so an empty map is interpreted as, "don't change anything." You can remove existing keys by explicitly setting each one to `null`.
