### ISSUE TITLE
Set the GitHub website url to https://metacontroller.app/

### ISSUE THREAD

**Issue by rlguarino** [GoogleCloudPlatform/metacontroller#74]
Its really convenient to have a website on the github title line for a repository. I personally look for a link there first, I'm sure some others do the same thing. It's more of a NIT than anything else and I would do it myself but I'm not a maintainer.

![image](https://user-images.githubusercontent.com/1321834/43406559-54a65236-93d1-11e8-8e32-7bf619068be4.png)

![image](https://user-images.githubusercontent.com/1321834/43406838-edd998aa-93d1-11e8-97bb-3980766ebe7f.png)

**Comment by enisoc** [comment]
Done, and thanks! I didn't know about that setting.
