### ISSUE TITLE
Feature Request: add support for adding/removing finalizer

### ISSUE THREAD

**Issue by lionelvillard** [GoogleCloudPlatform/metacontroller#89]
The decorator controller can only add/remove labels/annotations. I have a usecase where I need to add/remove finalizers. The decorator controller seems the right place to do this.

**Comment by enisoc** [comment]
In #60, we're considering a related feature: you give us a `finalize` hook, and we'll add/remove the finalizer for you and call your hook as needed. The idea is to encapsulate the end-to-end flow of implementing a finalizer so we can own all the potentially tricky bits, in keeping with Metacontroller's philosophy of being "controllers on rails". Would that work for your use case?

If not, can you describe more about your use case for adding/removing finalizers manually? For example, are you intending to manipulate finalizer tags that are implemented by other controllers?

**Comment by lionelvillard** [comment]
The solution described in #60 is exactly what I need!
